#!/usr/bin/env bash

gc_dns_post_receive_update_bind_config() {
	echo "Invoked git hook: ${BASH_SOURCE[0]} $@"

  sudo git --git-dir=/etc/bind/.git --work-tree=/etc/bind reset --hard HEAD
  # sudo git --git-dir=/etc/bind/.git --work-tree=/etc/bind fetch --all
  sudo git --git-dir=/etc/bind/.git --work-tree=/etc/bind pull && \
  sudo systemctl try-restart bind9 || \
  sudo systemctl try-restart named

  if [ $? -eq 0 ]; then
    echo "info: The bind DNS config has been updated, and the new config is now active."
  fi

  current_dir="$PWD"
  cd ~/git-server/discover-git-server-dns
  # git --git-dir=~/git-server/discover-git-server-dns/.git --work-tree=~/git-server/discover-git-server-dns fetch --all
  git --git-dir=~/git-server/discover-git-server-dns/.git --work-tree=~/git-server/discover-git-server-dns pull
  ./git-update-srv.sh
  cd "$current_dir"

	echo "The git hook finished successfully: ${BASH_SOURCE[0]} $@"

  return 0
}

gc_dns_post_receive_update_bind_config $@
